apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovetest-zhanyouyu-ns

metadata:
  name: lovetest-zhanyouyu
  namespace: lovetest-zhanyouyu-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/lovetest-zhanyouyu
  newTag: 1.0.5

commonLabels:
  app: lovetest-zhanyouyu
  managed-by: argocd


